# Generated by Django 3.2 on 2021-10-12 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookType1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.CharField(max_length=10)),
                ('bookname', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('pub_date', models.DateField()),
                ('price', models.FloatField()),
                ('cover_image', models.ImageField(upload_to='uploads/images/')),
                ('btype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.booktype1')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category1')),
            ],
        ),
    ]
