# Generated by Django 3.2 on 2021-10-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book1',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/'),
        ),
    ]
