# Generated by Django 3.2 on 2021-10-13 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_book1_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book1',
            name='bookid',
        ),
    ]
