# Generated by Django 3.2 on 2021-10-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_book1_bookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book1',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
